const formData = {
  id: 1,
  calculation: {
    price: " id pola od ilosci * 1.2 + surfaceTreatment * 0.8",
    deliveryDate: "quantity < 100 ? 14 : 31",
  },
  formElements: [
    {
      id: 1,
      type: "quantity",
      name: "Ilość",
      info: "",
      description: "",
      options: [],
      isImportant: true,
    },
    {
      id: 2,
      type: "selectGroup",
      name: "Jednostki",
      info: "",
      description: "",
      options: ["mm", "inch", "cm"],
      isImportant: false,
    },
    {
      id: 4,
      type: "selectGroup",
      name: "Rodzaj aluminium",
      info: "",
      description: "",
      options: ["Aluminium 5052", "Aluminium 6061"],
      isImportant: false,
    },
    {
      id: 5,
      type: "selectGroup",
      name: "Kolory",
      info: "",
      description: "",
      options: ["Srebrno-biały"],
      isImportant: false,
    },
    {
      id: 6,
      type: "selectGroup",
      name: "Grubość",
      info: "",
      description: "",
      options: [
        "0.8mm",
        "1.0mm",
        "1.2mm",
        "1.5mm",
        "2.0mm",
        "2.5mm",
        "3.0mm",
        "4.0mm",
      ],
      isImportant: true,
    },
    {
      id: 777,
      type: "selectMaterial",
      selectedMaterial: {
        image:
          "https://pcbwayfile.s3-us-west-2.amazonaws.com/web/20/12/10/2226459873337t.jpg",
        name: "Aluminum 12125052",
        infoLink: "#",
        rate: 4.9,
        rates: 2051,
      },
      data: {
        alertMesage: "Uważaj aby wybrać coś tam",

        categories: [
          {
            id: "surface",
            name: "Powierzchnia",
            options: [
              { id: "standard", name: "Standardowa (Frezowana)" },
              { id: "anodized", name: "Anodowana" },
              { id: "brushed", name: "Szczotkowana" },
              { id: "bead-blast", name: "Piaskowana" },
              { id: "spray-painting", name: "Malowanie natryskowe" },
              { id: "powder-coat", name: "Malowanie proszkowe" },
              { id: "spray-plating", name: "Natryskowe powlekanie" },
              { id: "detail-sanding", name: "Szlifowanie detali" },
            ],
          },
        ],
        tiles: [
          {
            id: "bead-blast-anodized",
            categoryId: "surface",
            name: "Piaskowanie + Anodowanie",
            description:
              "Anodowanie tworzy powłokę odporną na korozję. Części mogą być anodowane w różnych kolorach — przezroczysty, czarny, czerwony i złoty są najczęściej spotykane — i zwykle jest związane z aluminium. A dzięki piaskowaniu powierzchnia części pozostaje gładka, z matowym wyglądem.",
            image: "/placeholder.svg?height=150&width=250",
            colors: [
              "blue",
              "black",
              "gray",
              "yellow",
              "orange",
              "red",
              "teal",
              "purple",
              "brown",
              "beige",
            ],
            requiredOption: "anodized",
          },
          {
            id: "bead-blast-anodized12",
            categoryId: "surface",
            name: "Piaskowanie + b;lblblblb",
            description:
              "Anodowanie tworzy powłokę odporną na korozję. Części mogą być anodowane w różnych kolorach — przezroczysty, czarny, czerwony i złoty są najczęściej spotykane — i zwykle jest związane z aluminium. A dzięki piaskowaniu powierzchnia części pozostaje gładka, z matowym wyglądem.",
            image: "/placeholder.svg?height=150&width=250",
            colors: [
              "blue",
              "black",
              "gray",
              "yellow",
              "orange",
              "red",
              "teal",
              "purple",
              "brown",
              "beige",
            ],
            requiredOption: "anodized",
          },

          {
            id: "anodized-simple",
            categoryId: "surface",
            name: "Anodowanie",
            description:
              "Anodowanie tworzy powłokę odporną na korozję. Części mogą być anodowane w różnych kolorach — przezroczysty, czarny, czerwony i złoty są najczęściej spotykane — i zwykle jest związane z aluminium.",
            image: "/placeholder.svg?height=150&width=250",
            colors: [
              "blue",
              "black",
              "gray",
              "yellow",
              "orange",
              "red",
              "teal",
              "purple",
              "brown",
              "beige",
            ],
            requiredOption: "anodized",
          },
          {
            id: "standard-finish",
            categoryId: "surface",
            name: "Wykończenie standardowe",
            description:
              "Standardowe wykończenie frezowane zapewnia podstawową obróbkę powierzchni bez dodatkowego przetwarzania.",
            image: "/placeholder.svg?height=150&width=250",
            colors: [],
            requiredOption: "standard",
          },
          {
            id: "brushed-finish",
            categoryId: "surface",
            name: "Wykończenie szczotkowane",
            description:
              "Wykończenie szczotkowane tworzy serię drobnych linii na powierzchni, nadając jej charakterystyczny wygląd i teksturę.",
            image: "/placeholder.svg?height=150&width=250",
            colors: [],
            requiredOption: "brushed",
          },
        ],
      },
    },
    {
      id: 8,
      type: "uploadElement",
      name: "Rysunek techiczny",
      info: "",
      description: "",
      options: [],
      isImportant: false,
    },
    {
      id: 9,
      type: "radioElements",
      name: "Czy Twoje części wymagają gwintowania?",
      info: "",
      description:
        "Proszę określić, czy Twoja część ma gwinty wewnętrzne lub zewnętrzne.Nie ponosimy żadnego ryzyka montażowego, jeśli jest to niestandardowy gwint, chyba że wszystkie części montażowe są tutaj produkowane i montowane.",
      options: ["Nie", "Tak"],
      isImportant: true,
    },
    {
      id: 10,
      type: "radioElements",
      name: "Wkładki",
      info: "",
      description: "Proszę podać standardowe wkładki stosowane w  części.",
      options: ["Nie", "Tak"],
      isImportant: true,
    },
    {
      id: 11,
      type: "radioElements",
      name: "Tolerancja",
      info: "",
      decription:
        "Tolerancje będą kontrolowane zgodnie z normą ISO 2768-1. W przypadku innych, węższych tolerancji, wymagany będzie rysunek techniczny w celu wskazania krytycznych wymiarów.",
      options: [
        "Nie są wymagane żadne węższe tolerancje (ISO 2768-1)",
        "Wymagane są węższe tolerancje",
      ],
      isImportant: true,
    },
    {
      id: 12,
      type: "radioElements",
      name: "Spawanie",
      info: "",
      decription: "",
      options: ["Nie", "Tak"],
      isImportant: true,
    },
    {
      id: 13,
      type: "radioElements",
      name: "Oznaczenie części",
      info: "Proszę wyraźnie oznaczyć zawartość sitodruku lub grawerunku laserowego w pliku CAD (DWG lub DXF). Wymagany jest również plik graficzny (Ai lub SVG).",
      decription: "",
      options: ["Sitodruk", "Grawerowanie laserowe"],
      isImportant: false,
    },
    {
      id: 14,
      type: "radioElements",
      name: "Montaż części",
      info: "Jeśli wybierzesz [Test montażu], wymagany jest rysunek 2D z instrukcjami montażu. Wyniki testu montażu zostaną przesłane e-mailem. Domyślnie zostanie wykonany tylko test. Jeśli musisz wysłać je po montażu, wybierz [Wyślij w montażu].",
      decription:
        "Proszę określić wymagania dotyczące montażu. PCBWay nie ponosi żadnego ryzyka związanego z montażem, jeśli wybierzesz opcję Brak wymagań dotyczących montażu.",
      options: ["Nie", "Testy montażowe", "Dostawa w formie zmontowanej"],
      isImportant: true,
    },
    {
      id: 15,
      type: "radioElements",
      name: "Wygląd końcowy",
      info: "",
      decription: "",
      options: ["Standard", "Premium (dodatkowe opłaty)"],
      isImportant: false,
    },
    {
      id: 16,
      type: "radioElements",
      name: "Kontrola",
      info: "",
      decription:
        "Raport z inspekcji nie zostanie wysłany wraz z częściami, chyba że będzie Ci potrzebny.",
      options: [
        "Standardowa inspekcja (brak raportu)",
        "Standardowa inspekcja z formalnym raportem",
        "Inspekcja CMM z formalnym raportem",
        "Certyfikacja materiału źródłowego",
      ],
      isImportant: false,
    },
    {
      id: 17,
      type: "selectGroup",
      name: "Opis produktu",
      info: "Opis produktu wymagany do odprawy celnej:1. Przestrzegaj zasad handlu międzynarodowego i podaj opisy produktów do odprawy celnej.2. Wybierz prawidłowy opis produktu zgodnie z rzeczywistym zastosowaniem produktu. Jeśli nie ma pasującego elementu, wybierz Inne.",
      decription: "",
      options: [
        "Sprzęt biurowy i akcesoria",
        "Pojazdy i akcesoria",
        "Rozrywka DIY",
        "Sprzęt audio i wideo",
      ],
      isImportant: true,
    },
    {
      id: 18,
      type: "textArea",
      name: "Inne specjalne wymagania",
      info: "",
      decription:
        "Wypełnij wymaganiami dotyczącymi produkcji, pakowania i dostarczenia",
      options: [],
      isImportant: false,
    },
  ],
};

export default formData;
