const formData = {
  id: 1,
  formElements: [
    {
        id: 1,
        type: "selectGroup",
        name: "Ilość",
        info: "jakas informacja wazna",
        description:"",
        options: [],
        isImportant: true,
      },
    {
      id: 2,
      type: "selectGroup",
      name: "Jednostki",
      info: "jakas informacja wazna",
      description:"",
      options: ["mm", "inch", "cm"],
      isImportant: false,
    },
    {
      id: 3,
      type: "selectGroup",
      name: "Materiał",
      info: "jakas informacja wazna",
      description:"",
      options: ["Aluminium", "Stal nierdzewna","Stal miękka" ,"Miedź","PMMA(Akryl)","Włókno węglowe"],
      isImportant: true,
    },
    {
        id: 4,
        type: "selectGroup",
        name: "Rodzaj",
        info: "",
        description:"",
        options: ["Aluminium 5052", "Aluminium 6061"],
        isImportant: false,
      },
    {
        id: 5,
        type: "selectGroup",
        name: "Kolory",
        info: "",
        description:"",
        options: ["Srebrno-biały"],
        isImportant: false,
    },
    {
        id: 6,
        type: "radioElements",
        name: "Grubość",
        info: "jakas informacja wazna",
        description:"",
        options: ["0.8mm","1.0mm","1.2mm","1.5mm","2.0mm","2.5mm","3.0mm","4.0mm"],
        isImportant: true,
    },
    // {
    //     id: 6,
    //     type: "radioElements",
    //     name: "Grubość",
    //     info: "jakas informacja wazna",
    //     options: ["0.8mm","1.0mm","1.2mm","1.5mm","2.0mm","2.5mm","3.0mm","4.0mm"],
    //     isImportant: true,
    // },
    {
        id: 8,
        type: "uploadElement",
        name: "Rysunek techiczny",
        info: "jakas informacja wazna",
        description:"",
        options: [],
        isImportant: false,
    },
    {
        id: 9,
        type: "radioElements",
        name: "Czy Twoje części wymagają gwintowania?",
        info: "jakas informacja wazna",
        description:"Proszę określić, czy Twoja część ma gwinty wewnętrzne lub zewnętrzne. PCBWay nie ponosi żadnego ryzyka montażowego, jeśli jest to niestandardowy gwint, chyba że wszystkie części montażowe są tutaj produkowane i montowane.",
        options: ["Nie","Tak"],
        isImportant: true,
    },
    {
        id: 10,
        type: "radioElements",
        name: "Wkładki",
        info: "jakas informacja wazna",
        description:"Proszę podać standardowe wkładki stosowane w Państwa części.",
        options: ["Nie","Tak"],
        isImportant: true,
    },
    {
        id: 11,
        type: "radioElements",
        name: "Tolerancja",
        info: "jakas informacja wazna",
        decription:"Tolerancje będą kontrolowane zgodnie z normą ISO 2768-1. W przypadku innych, węższych tolerancji, wymagany będzie rysunek techniczny w celu wskazania krytycznych wymiarów.",
        options: ["Nie są wymagane żadne węższe tolerancje (ISO 2768-1)","Wymagane są węższe tolerancje"],
        isImportant: true,
    },
    {
        id: 12,
        type: "radioElements",
        name: "Spawanie",
        info: "jakas informacja wazna",
        decription:"",
        options: ["Nie","Tak"],
        isImportant: true,
    },
    {
        id: 13,
        type: "radioElements",
        name: "Oznaczenie części",
        info: "Proszę wyraźnie oznaczyć zawartość sitodruku lub grawerunku laserowego w pliku CAD (DWG lub DXF). Wymagany jest również plik graficzny (Ai lub SVG).",
        decription:"",
        options: ["Sitodruk","Grawerowanie laserowe"],
        isImportant: false,
    },
    {
        id: 14,
        type: "radioElements",
        name: "Montaż części",
        info: "Jeśli wybierzesz [Test montażu], wymagany jest rysunek 2D z instrukcjami montażu. Wyniki testu montażu zostaną przesłane e-mailem. Domyślnie zostanie wykonany tylko test. Jeśli musisz wysłać je po montażu, wybierz [Wyślij w montażu].",
        decription:"Proszę określić wymagania dotyczące montażu. PCBWay nie ponosi żadnego ryzyka związanego z montażem, jeśli wybierzesz opcję Brak wymagań dotyczących montażu.",
        options: ["Nie","Testy montażowe","Dostawa w formie zmontowanej"],
        isImportant: true,
    },
    {
        id: 15,
        type: "radioElements",
        name: "Wygląd końcowy",
        info: "",
        decription:"",
        options: ["Standard","Premium (dodatkowe opłaty)"],
        isImportant: false,
    },
    {
        id: 16,
        type: "radioElements",
        name: "Kontrola",
        info: "",
        decription:"Raport z inspekcji nie zostanie wysłany wraz z częściami, chyba że będzie Ci potrzebny.",
        options: ["Standardowa inspekcja (brak raportu)","Standardowa inspekcja z formalnym raportem","Inspekcja CMM z formalnym raportem","Certyfikacja materiału źródłowego"],
        isImportant: false,
    },
    {
        id: 17,
        type: "selectGroup",
        name: "Opis produktu",
        info: "Opis produktu wymagany do odprawy celnej:1. Przestrzegaj zasad handlu międzynarodowego i podaj opisy produktów do odprawy celnej.2. Wybierz prawidłowy opis produktu zgodnie z rzeczywistym zastosowaniem produktu. Jeśli nie ma pasującego elementu, wybierz Inne.",
        decription:"",
        options: ["Sprzęt biurowy i akcesoria","Pojazdy i akcesoria","Rozrywka DIY","Sprzęt audio i wideo"],
        isImportant: true,
    },
    {
        id: 18,
        type: "textArea",
        name: "Inne specjalne wymagania",
        info: "",
        decription:"Wypełnij wymaganiami dotyczącymi produkcji, pakowania i dostarczenia",
        options: [],
        isImportant: false,
    },
  ],
};

export default formData;
