import type { CartElementType, FormDataToGenerateType, FilledFormType } from "@/types"

// Sample form data based on the provided structure
export const mockCartData: CartElementType[] = [
  {
    id: 1,
    filledForm: {
      id: 1,
      uploadedFiles: [],
      values: [
        { id: 1, value: 123 },
        { id: 2, value: "inch" },
        { id: 4, value: "Aluminium 5052" },
        { id: 5, value: "Srebrno-biały" },
        { id: 6, value: "0.8mm" },
        { id: 777, value: { category: "surface", option: "anodized", tile: "anodized-simple", color: "black" } },
        { id: 8, value: [] },
        { id: 9, value: "Tak" },
        { id: 10, value: "Tak" },
        { id: 11, value: "Nie są wymagane żadne węższe tolerancje (ISO 2768-1)" },
        { id: 12, value: "Tak" },
        { id: 13, value: "Grawerowanie laserowe" },
        { id: 14, value: "Testy montażowe" },
        { id: 15, value: "Premium (dodatkowe opłaty)" },
        { id: 16, value: "Standardowa inspekcja (brak raportu)" },
        { id: 17, value: "Sprzęt biurowy i akcesoria" },
        { id: 18, value: "Dodatkowe uwagi do zamówienia" },
      ],
    } as FilledFormType,
    formDataToGenerate: {
      id: 1,
      calculation: {
        price: "id pola od ilosci * 1.2 + surfaceTreatment * 0.8",
        deliveryDate: "quantity < 100 ? 14 : 31",
      },
      values: [
        { id: 1, type: "quantity", name: "Ilość", info: "", description: "", options: [], isImportant: true },
        {
          id: 2,
          type: "selectGroup",
          name: "Jednostki",
          info: "",
          description: "",
          options: ["mm", "inch", "cm"],
          isImportant: false,
        },
        {
          id: 4,
          type: "selectGroup",
          name: "Rodzaj aluminium",
          info: "",
          description: "",
          options: ["Aluminium 5052", "Aluminium 6061"],
          isImportant: false,
        },
        {
          id: 5,
          type: "selectGroup",
          name: "Kolory",
          info: "",
          description: "",
          options: ["Srebrno-biały"],
          isImportant: false,
        },
        {
          id: 6,
          type: "selectGroup",
          name: "Grubość",
          info: "",
          description: "",
          options: ["0.8mm", "1.0mm", "1.2mm", "1.5mm", "2.0mm", "2.5mm", "3.0mm", "4.0mm"],
          isImportant: true,
        },
        {
          id: 777,
          type: "selectMaterial",
          name: "Powierzchnia",
          info: "",
          description: "",
          options: [],
          isImportant: true,
        },
        {
          id: 8,
          type: "uploadElement",
          name: "Rysunek techiczny",
          info: "",
          description: "",
          options: [],
          isImportant: false,
        },
        {
          id: 9,
          type: "radioElements",
          name: "Czy Twoje części wymagają gwintowania?",
          info: "",
          description: "",
          options: ["Nie", "Tak"],
          isImportant: true,
        },
        {
          id: 10,
          type: "radioElements",
          name: "Wkładki",
          info: "",
          description: "",
          options: ["Nie", "Tak"],
          isImportant: true,
        },
        {
          id: 11,
          type: "radioElements",
          name: "Tolerancja",
          info: "",
          description: "",
          options: ["Nie są wymagane żadne węższe tolerancje (ISO 2768-1)", "Wymagane są węższe tolerancje"],
          isImportant: true,
        },
        {
          id: 12,
          type: "radioElements",
          name: "Spawanie",
          info: "",
          description: "",
          options: ["Nie", "Tak"],
          isImportant: true,
        },
        {
          id: 13,
          type: "radioElements",
          name: "Oznaczenie części",
          info: "",
          description: "",
          options: ["Sitodruk", "Grawerowanie laserowe"],
          isImportant: false,
        },
        {
          id: 14,
          type: "radioElements",
          name: "Montaż części",
          info: "",
          description: "",
          options: ["Nie", "Testy montażowe", "Dostawa w formie zmontowanej"],
          isImportant: true,
        },
        {
          id: 15,
          type: "radioElements",
          name: "Wygląd końcowy",
          info: "",
          description: "",
          options: ["Standard", "Premium (dodatkowe opłaty)"],
          isImportant: false,
        },
        {
          id: 16,
          type: "radioElements",
          name: "Kontrola",
          info: "",
          description: "",
          options: [
            "Standardowa inspekcja (brak raportu)",
            "Standardowa inspekcja z formalnym raportem",
            "Inspekcja CMM z formalnym raportem",
            "Certyfikacja materiału źródłowego",
          ],
          isImportant: false,
        },
        {
          id: 17,
          type: "selectGroup",
          name: "Opis produktu",
          info: "",
          description: "",
          options: ["Sprzęt biurowy i akcesoria", "Pojazdy i akcesoria", "Rozrywka DIY", "Sprzęt audio i wideo"],
          isImportant: true,
        },
        {
          id: 18,
          type: "textArea",
          name: "Inne specjalne wymagania",
          info: "",
          description: "",
          options: [],
          isImportant: false,
        },
      ],
      defaultFilledFormData: {} as FilledFormType,
    } as FormDataToGenerateType,
  },
  {
    id: 2,
    filledForm: {
      id: 2,
      uploadedFiles: [],
      values: [
        { id: 1, value: 50 },
        { id: 2, value: "mm" },
        { id: 4, value: "Aluminium 6061" },
        { id: 5, value: "Srebrno-biały" },
        { id: 6, value: "1.5mm" },
        { id: 777, value: { category: "surface", option: "standard", tile: "standard-finish", color: "" } },
        { id: 8, value: [] },
        { id: 9, value: "Nie" },
        { id: 10, value: "Nie" },
        { id: 11, value: "Nie są wymagane żadne węższe tolerancje (ISO 2768-1)" },
        { id: 12, value: "Nie" },
        { id: 13, value: "Sitodruk" },
        { id: 14, value: "Nie" },
        { id: 15, value: "Standard" },
        { id: 16, value: "Standardowa inspekcja (brak raportu)" },
        { id: 17, value: "Pojazdy i akcesoria" },
        { id: 18, value: "Proszę o dokładne sprawdzenie wymiarów" },
      ],
    } as FilledFormType,
    formDataToGenerate: {
      id: 2,
      calculation: {
        price: "id pola od ilosci * 1.2 + surfaceTreatment * 0.8",
        deliveryDate: "quantity < 100 ? 14 : 31",
      },
      values: [
        { id: 1, type: "quantity", name: "Ilość", info: "", description: "", options: [], isImportant: true },
        {
          id: 2,
          type: "selectGroup",
          name: "Jednostki",
          info: "",
          description: "",
          options: ["mm", "inch", "cm"],
          isImportant: false,
        },
        {
          id: 4,
          type: "selectGroup",
          name: "Rodzaj aluminium",
          info: "",
          description: "",
          options: ["Aluminium 5052", "Aluminium 6061"],
          isImportant: false,
        },
        {
          id: 5,
          type: "selectGroup",
          name: "Kolory",
          info: "",
          description: "",
          options: ["Srebrno-biały"],
          isImportant: false,
        },
        {
          id: 6,
          type: "selectGroup",
          name: "Grubość",
          info: "",
          description: "",
          options: ["0.8mm", "1.0mm", "1.2mm", "1.5mm", "2.0mm", "2.5mm", "3.0mm", "4.0mm"],
          isImportant: true,
        },
        {
          id: 777,
          type: "selectMaterial",
          name: "Powierzchnia",
          info: "",
          description: "",
          options: [],
          isImportant: true,
        },
        {
          id: 8,
          type: "uploadElement",
          name: "Rysunek techiczny",
          info: "",
          description: "",
          options: [],
          isImportant: false,
        },
        {
          id: 9,
          type: "radioElements",
          name: "Czy Twoje części wymagają gwintowania?",
          info: "",
          description: "",
          options: ["Nie", "Tak"],
          isImportant: true,
        },
        {
          id: 10,
          type: "radioElements",
          name: "Wkładki",
          info: "",
          description: "",
          options: ["Nie", "Tak"],
          isImportant: true,
        },
        {
          id: 11,
          type: "radioElements",
          name: "Tolerancja",
          info: "",
          description: "",
          options: ["Nie są wymagane żadne węższe tolerancje (ISO 2768-1)", "Wymagane są węższe tolerancje"],
          isImportant: true,
        },
        {
          id: 12,
          type: "radioElements",
          name: "Spawanie",
          info: "",
          description: "",
          options: ["Nie", "Tak"],
          isImportant: true,
        },
        {
          id: 13,
          type: "radioElements",
          name: "Oznaczenie części",
          info: "",
          description: "",
          options: ["Sitodruk", "Grawerowanie laserowe"],
          isImportant: false,
        },
        {
          id: 14,
          type: "radioElements",
          name: "Montaż części",
          info: "",
          description: "",
          options: ["Nie", "Testy montażowe", "Dostawa w formie zmontowanej"],
          isImportant: true,
        },
        {
          id: 15,
          type: "radioElements",
          name: "Wygląd końcowy",
          info: "",
          description: "",
          options: ["Standard", "Premium (dodatkowe opłaty)"],
          isImportant: false,
        },
        {
          id: 16,
          type: "radioElements",
          name: "Kontrola",
          info: "",
          description: "",
          options: [
            "Standardowa inspekcja (brak raportu)",
            "Standardowa inspekcja z formalnym raportem",
            "Inspekcja CMM z formalnym raportem",
            "Certyfikacja materiału źródłowego",
          ],
          isImportant: false,
        },
        {
          id: 17,
          type: "selectGroup",
          name: "Opis produktu",
          info: "",
          description: "",
          options: ["Sprzęt biurowy i akcesoria", "Pojazdy i akcesoria", "Rozrywka DIY", "Sprzęt audio i wideo"],
          isImportant: true,
        },
        {
          id: 18,
          type: "textArea",
          name: "Inne specjalne wymagania",
          info: "",
          description: "",
          options: [],
          isImportant: false,
        },
      ],
      defaultFilledFormData: {} as FilledFormType,
    } as FormDataToGenerateType,
  },
]

